### ISSUE TITLE
backup.yml always drops existing DB

### ISSUE THREAD

**Issue by k2s** [isaacsimmons/ansible-role-ttrss#2]
this is critical issue with this role
it should be possible to apply this role multiple times to server and it should not destroy the DB if already exists

the problem is in "init db schema" task which should be executed only if "Create ttrss postgres database" created new database.

the ttrss_schema_pgsql.sql contains DROP commands

**Comment by isaacsimmons** [comment]
The "creates" flag coupled with `&& touch /root/ttrss_schema_loaded` ought to prevent the task from running more than once on a server.

Under what workflow are you encountering the destructive behavior?
